[package]
name = "mf2_parser"
description = "Parser and AST definitions for MessageFormat 2"
categories = ["parser-implementations"]
version = "0.1.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
